[package]
name = "everyone"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serenity = "0.12.4"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
tokio-cron-scheduler = "0.13.0"